#!/bin/bash

set -ex

RELEASE=$(lsb_release -r -s | awk -F. '{print $1}')

if [ $RELEASE -lt 16 ]; then
    STOP_REQUIRED=True
fi

debconf-set-selections <<EOF
slapd slapd/internal/adminpw password crapper
slapd slapd/password1 password crapper
slapd slapd/password2 password crapper
slapd slapd/domain string test.com
slapd shared/organization string test
EOF

apt -y install slapd ldap-utils phpldapadmin

sed -i "s/dc=example/dc=test/g" /etc/phpldapadmin/config.php
service apache2 restart

if [ $STOP_REQUIRED ]; then
    service slapd stop
fi

slapadd -v -c -l files/backup.ldif

if [ $STOP_REQUIRED ]; then
    service slapd start
fi

status-set 'active' 'Unit is ready'
