#!/bin/bash

set -ex

debconf-set-selections <<EOF
slapd slapd/internal/adminpw password crapper
slapd slapd/password1 password crapper
slapd slapd/password2 password crapper
slapd slapd/domain string test.com
slapd shared/organization string test
EOF

apt -y install slapd ldap-utils phpldapadmin

sed -i "s/dc=example/dc=test/g" /etc/phpldapadmin/config.php
service apache2 restart

slapadd -v -c -l files/backup.ldif

status-set 'active' 'Unit is ready'
